FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD stockton2.jar /opt/stockton2/
EXPOSE 8080
WORKDIR /opt/stockton2/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "stockton2.jar"]
